### PR TITLE
feat: add mongo and redis protcol support

### PR DESCRIPTION
**Pull request by Jamlee**
support mongo statement and redis command display. for example: 
````
tproxy -l 0.0.0.0  -p 27018 -r 127.0.0.1:27017 -t mongo 

...
22:06:37.707 [5] Accepted from: 127.0.0.1:56999
22:06:37.707 [5] Connected to server: 127.0.0.1:27017
22:06:37.707 | cli -> ser | [Query] [coll:admin.$cmd] {"getnonce":1} 
22:06:37.707 | cli -> ser | [Query] [coll:admin.$cmd] {"client":{"driver":{"name":"mgo","version":"globalsign"},"os":{"architecture":"amd64","type":"linux"}},"isMaster":1} 
22:06:37.710 | cli -> ser | [Query] [coll:admin.$cmd] {"ping":1} 
...
````

````
tproxy -l 0.0.0.0  -p 6380 -r 127.0.0.1:6379 -t redis

21:56:42.952 Listening on [::]:6380...
21:56:43.358 [1] Accepted from: 192.168.31.10:58658
21:56:43.358 [1] Connected to server: 127.0.0.1:26379
21:56:43.359 auth xxxxxskNvemwRyz7jbAtt27AOxL3SLH
21:56:43.359 sentinel get-master-addr-by-name default
21:56:43.359 192.168.31.10 6379
21:56:43.359 sentinel sentinels default
...
````

there are a lot of code from https://github.com/40t/go-sniffer.

### CODE REVIEW

**Comment by Jamlee** [comment]
there are  error in unchanged code:
https://github.com/kevwan/tproxy/pull/18/files#annotation_8586091168

**Comment by kevwan** [comment]
> there are error in unchanged code: https://github.com/kevwan/tproxy/pull/18/files#annotation_8586091168

I'll fix it. Thanks!

**Comment by kevwan** [comment]
@Jamlee it panics when I use the latest redis. PTAL.

**Comment by Jamlee** [comment]
i tried by ioredis unit test. @kevwan  Could you provide more information how to  repduce ?
```
docker run -d --name myredis -p 6380:6379 redis:6.2.7
./tproxy -l 0.0.0.0 -p 6379 -r 127.0.0.1:6380 -t redis
git clone https://github.com/luin/ioredis.git
cd ioredis
npm run test
```

**Comment by kevwan** [comment]
> i tried by ioredis unit test. @kevwan  Could you provide more information how to  repduce ?
> 
> ```
> 
> docker run -d --name myredis -p 6380:6379 redis:6.2.7
> 
> ./tproxy -l 0.0.0.0 -p 6379 -r 127.0.0.1:6380 -t redis
> 
> git clone https://github.com/luin/ioredis.git
> 
> cd ioredis
> 
> npm run test
> 
> ```

Sure, later.

**Comment by kevwan** [comment]
image

```shell
tproxy -p 6380 -r localhost:6379 -t redis
```

**Pull request merged**
