### PR TITLE
feat: add mysql protocol, surport client and server parse.

### PR DESCRIPTION
**Pull request by hidakafinzelz**

### CODE REVIEW

**Review by kevwan — APPROVED** [review]

**Comment by kevwan** [comment]
Please remove unused code to avoid staticcheck errors.

**Comment by hidakafinzelz** [comment]
> Please remove unused code to avoid staticcheck errors.

Hi, I removed unused code in a new commit.

**Comment by kevwan** [comment]
Would you please explain why only process client?

**Comment by hidakafinzelz** [comment]
> Would you please explain why only process client?

for response body may large

**Comment by kevwan** [comment]
> > Would you please explain why only process client?
> 
> for response body may large

But if the response body is not large, and I want to check the response body, how to do it?

**Comment by hidakafinzelz** [comment]
> > > Would you please explain why only process client?
> > 
> > 
> > for response body may large
> 
> But if the response body is not large, and I want to check the response body, how to do it?

You are right, I will improve it later ,and define a max response body which can be checked like 1MB. Any recommend you have? Thanks.

**Comment by hidakafinzelz** [comment]
Hi, I process response data in thie new commit (c3599c961b57048fab048ddbe6a5eab3d2c79154). 
企业微信截图_17276792307011

**Review by kevwan — APPROVED** [review]

**Pull request merged**
